// <auto-generated />
namespace Journly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ValidationForJournals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationForJournals));
        
        string IMigrationMetadata.Id
        {
            get { return "201710090407499_ValidationForJournals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
